/*
 * Cat Insurance API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// EmployeeAPIService is a service that implements the logic for the EmployeeAPIServicer
// This service should implement the business logic for every endpoint for the EmployeeAPI API.
// Include any external packages or services that will be required by this service.
type EmployeeAPIService struct {
}

// NewEmployeeAPIService creates a default api service
func NewEmployeeAPIService() EmployeeAPIServicer {
	return &EmployeeAPIService{}
}

// CreateEmployee - Create a new employee
func (s *EmployeeAPIService) CreateEmployee(ctx context.Context, employeeReq EmployeeReq) (ImplResponse, error) {
	// TODO - update CreateEmployee with the required logic for this service method.
	// Add api_employee_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, EmployeeRes{}) or use other options such as http.Ok ...
	// return Response(201, EmployeeRes{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateEmployee method not implemented")
}

// GetEmployee - Get employee details
func (s *EmployeeAPIService) GetEmployee(ctx context.Context, employeeId string) (ImplResponse, error) {
	// TODO - update GetEmployee with the required logic for this service method.
	// Add api_employee_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EmployeeRes{}) or use other options such as http.Ok ...
	// return Response(200, EmployeeRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetEmployee method not implemented")
}

// UpdateEmployee - Update an employee
func (s *EmployeeAPIService) UpdateEmployee(ctx context.Context, employeeReq EmployeeReq) (ImplResponse, error) {
	// TODO - update UpdateEmployee with the required logic for this service method.
	// Add api_employee_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateEmployee method not implemented")
}
