/*
 * Cat Insurance API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BankDetails struct {
	Iban string `json:"iban"`

	Bic string `json:"bic"`

	Name string `json:"name"`

	Id string `json:"id"`
}

// AssertBankDetailsRequired checks if the required fields are not zero-ed
func AssertBankDetailsRequired(obj BankDetails) error {
	elements := map[string]interface{}{
		"iban": obj.Iban,
		"bic":  obj.Bic,
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertBankDetailsConstraints checks if the values respects the defined constraints
func AssertBankDetailsConstraints(obj BankDetails) error {
	return nil
}
