/*
 * Cat Insurance API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	ContractAPIService := openapi.NewContractAPIService()
	ContractAPIController := openapi.NewContractAPIController(ContractAPIService)

	CustomerAPIService := openapi.NewCustomerAPIService()
	CustomerAPIController := openapi.NewCustomerAPIController(CustomerAPIService)

	EmployeeAPIService := openapi.NewEmployeeAPIService()
	EmployeeAPIController := openapi.NewEmployeeAPIController(EmployeeAPIService)

	router := openapi.NewRouter(ContractAPIController, CustomerAPIController, EmployeeAPIController)

	log.Fatal(http.ListenAndServe(":8081", router))
}
