/*
 * Cat Insurance API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type EmployeeReq struct {

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	Address Address `json:"address"`
}

// AssertEmployeeReqRequired checks if the required fields are not zero-ed
func AssertEmployeeReqRequired(obj EmployeeReq) error {
	elements := map[string]interface{}{
		"firstName": obj.FirstName,
		"lastName": obj.LastName,
		"address": obj.Address,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertAddressRequired(obj.Address); err != nil {
		return err
	}
	return nil
}

// AssertEmployeeReqConstraints checks if the values respects the defined constraints
func AssertEmployeeReqConstraints(obj EmployeeReq) error {
	return nil
}
