/*
 * Cat Insurance API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type CustomerRes struct {

	Id string `json:"id"`

	Email string `json:"email"`

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	Title string `json:"title,omitempty"`

	FamilyStatus string `json:"familyStatus"`

	BirthDate string `json:"birthDate"`

	SocialSecurityNumber string `json:"socialSecurityNumber"`

	TaxId string `json:"taxId"`

	JobStatus string `json:"jobStatus"`

	Address Address `json:"address"`

	BankDetails BankDetails `json:"bankDetails"`
}

// AssertCustomerResRequired checks if the required fields are not zero-ed
func AssertCustomerResRequired(obj CustomerRes) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"email": obj.Email,
		"firstName": obj.FirstName,
		"lastName": obj.LastName,
		"familyStatus": obj.FamilyStatus,
		"birthDate": obj.BirthDate,
		"socialSecurityNumber": obj.SocialSecurityNumber,
		"taxId": obj.TaxId,
		"jobStatus": obj.JobStatus,
		"address": obj.Address,
		"bankDetails": obj.BankDetails,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertAddressRequired(obj.Address); err != nil {
		return err
	}
	if err := AssertBankDetailsRequired(obj.BankDetails); err != nil {
		return err
	}
	return nil
}

// AssertCustomerResConstraints checks if the values respects the defined constraints
func AssertCustomerResConstraints(obj CustomerRes) error {
	return nil
}
