name: meowmed
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  openapi:
    path: ../openapi
  rxdart:
  logger: ^2.0.2+1
  date_field: 4.0.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.11
  http: ^1.2.1
  # injectable:
  # get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # injectable_generator:
  # build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/MeowcroservicesLogoNew.png
