/*
 * Cat Insurance API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"errors"
)

type RateRes struct {
	Rate float32 `json:"rate,omitempty"`
}

// AssertRateResRequired checks if the required fields are not zero-ed
func AssertRateResRequired(obj RateRes) error {
	return nil
}

// AssertRateResConstraints checks if the values respects the defined constraints
func AssertRateResConstraints(obj RateRes) error {
	if obj.Rate < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Rate > 99999 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	return nil
}
